

# This is a basic workflow to help you get started with Actions

name: Cloud Custodian Run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  custodian:
    name: 'Cloud Custodian Run'
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
          architecture: x64

      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_SA_KEY }}

      - name: Run Cloud Custodian
        run: |
          pip install -r cloud-custodian/requirements.txt
          c7n-org run -c cloud-custodian/environments/gcp.yml -s output -u cloud-custodian/policies/gcp.yml