

# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TF_DIR: ./terraform

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: false
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: false
        working-directory: ${{ env.TF_DIR }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_SA_KEY }}

      - name: Terraform Plan
        id: plan
        #if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: false
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_DIR }}